name: Release
on:
  push:
    tags:
    - '*'
jobs:

  build:
    uses: ./.github/workflows/ci.yml

  release:
    needs: build
    runs-on: self-hosted-ubuntu
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Compress artifacts
      shell: bash
      run: |
        ls -lha ./artifacts
        mkdir assets
        for $DIR in ./artifacts; do
          tar czf "assets/$DIR.tar.gz" "./artifacts/$DIR"
        done
        ls -lha ./assets
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create --repo "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME"  ./assets/*

